# These are supported funding model platforms

github: [exostruction]
# patreon: exoauth
# open_collective: exoauth
# ko_fi: exoauth
# tidelift: npm/exoauth
# community_bridge: exoauth
# liberapay: exoauth
# issuehunt: exoauth
# lfx_crowdfunding: exoauth
# polar: exoauth
# buy_me_a_coffee: exoauth
custom: # ['https://exoauth.com/sponsor']
