// <auto-generated />
using System;
using System.Text.Json;
using ExoAuth.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExoAuth.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229104454_AddSystemInviteLanguage")]
    partial class AddSystemInviteLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExoAuth.Domain.Entities.DeviceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("browser");

                    b.Property<string>("BrowserVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("browser_version");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_fingerprint");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsTrusted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_trusted");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operating_system");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("os_version");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_device_sessions");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_device_sessions_device_id");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("i_x_device_sessions_is_revoked");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("i_x_device_sessions_last_activity_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_device_sessions_user_id");

                    b.HasIndex("UserId", "DeviceId")
                        .HasDatabaseName("i_x_device_sessions_user_id_device_id");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("i_x_device_sessions_user_id_is_revoked");

                    b.ToTable("device_sessions", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.MfaBackupCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_mfa_backup_codes");

                    b.HasIndex("UserId", "IsUsed")
                        .HasDatabaseName("i_x__mfa_backup_codes__user_id__is_used");

                    b.ToTable("mfa_backup_codes", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_password_reset_tokens");

                    b.HasIndex("CodeHash")
                        .HasDatabaseName("i_x_password_reset_tokens_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_password_reset_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_password_reset_tokens_user_id");

                    b.HasIndex("UserId", "IsUsed", "ExpiresAt")
                        .HasDatabaseName("i_x_password_reset_tokens_user_id_is_used_expires_at");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_info");

                    b.Property<Guid?>("DeviceSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_session_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<bool>("RememberMe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("remember_me");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("SystemUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_user_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("DeviceSessionId")
                        .HasDatabaseName("i_x_refresh_tokens_device_session_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_refresh_tokens_expires_at");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("i_x_refresh_tokens_is_revoked");

                    b.HasIndex("SystemUserId")
                        .HasDatabaseName("i_x_refresh_tokens_system_user_id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("i_x_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_refresh_tokens_user_id");

                    b.HasIndex("UserType")
                        .HasDatabaseName("i_x_refresh_tokens_user_type");

                    b.HasIndex("UserId", "UserType", "IsRevoked")
                        .HasDatabaseName("i_x_refresh_tokens_user_id_user_type_is_revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_system_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("i_x_system_audit_logs_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_system_audit_logs_created_at");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("i_x_system_audit_logs_entity_type");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("i_x_system_audit_logs_target_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_system_audit_logs_user_id");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("i_x_system_audit_logs_action_created_at");

                    b.ToTable("system_audit_logs", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<JsonDocument>("PermissionIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permission_ids");

                    b.Property<DateTime?>("ResentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resent_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_system_invites");

                    b.HasIndex("AcceptedAt")
                        .HasDatabaseName("i_x_system_invites_accepted_at");

                    b.HasIndex("Email")
                        .HasDatabaseName("i_x_system_invites_email");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_system_invites_expires_at");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("i_x_system_invites_invited_by");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("i_x_system_invites_revoked_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_system_invites_token_hash");

                    b.ToTable("system_invites", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_system_permissions");

                    b.HasIndex("Category")
                        .HasDatabaseName("i_x_system_permissions_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_system_permissions_name");

                    b.ToTable("system_permissions", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymized");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mfa_enabled");

                    b.Property<DateTime?>("MfaEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enabled_at");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mfa_secret");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en")
                        .HasColumnName("preferred_language");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_system_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_system_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_system_users_is_active");

                    b.HasIndex("MfaEnabled")
                        .HasDatabaseName("i_x_system_users_mfa_enabled");

                    b.ToTable("system_users", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemUserPermission", b =>
                {
                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_user_id");

                    b.Property<Guid>("SystemPermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_permission_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("SystemUserId", "SystemPermissionId")
                        .HasName("p_k_system_user_permissions");

                    b.HasIndex("SystemPermissionId")
                        .HasDatabaseName("i_x_system_user_permissions_system_permission_id");

                    b.HasIndex("SystemUserId")
                        .HasDatabaseName("i_x_system_user_permissions_system_user_id");

                    b.ToTable("system_user_permissions", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.DeviceSession", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_device_sessions_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.MfaBackupCode", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany("MfaBackupCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_mfa_backup_codes_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_password_reset_tokens_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.DeviceSession", "DeviceSession")
                        .WithMany()
                        .HasForeignKey("DeviceSessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_refresh_tokens_device_sessions_device_session_id");

                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SystemUserId")
                        .HasConstraintName("f_k_refresh_tokens_system_users_system_user_id");

                    b.Navigation("DeviceSession");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemAuditLog", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_system_audit_logs_system_users_target_user_id");

                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_system_audit_logs_system_users_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemInvite", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_system_invites_system_users_invited_by");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemUserPermission", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemPermission", "SystemPermission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("SystemPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_system_user_permissions_system_permissions_system_permissio~");

                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "SystemUser")
                        .WithMany("Permissions")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_system_user_permissions_system_users_system_user_id");

                    b.Navigation("SystemPermission");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemPermission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemUser", b =>
                {
                    b.Navigation("MfaBackupCodes");

                    b.Navigation("Permissions");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
