// <auto-generated />
using System;
using System.Text.Json;
using ExoAuth.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExoAuth.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExoAuth.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ApprovalAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("approval_attempts");

                    b.Property<string>("ApprovalCodeHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approval_code_hash");

                    b.Property<DateTime?>("ApprovalExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approval_expires_at");

                    b.Property<string>("ApprovalTokenHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approval_token_hash");

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("browser");

                    b.Property<string>("BrowserVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("browser_version");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_type");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operating_system");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("os_version");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RiskFactors")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("risk_factors");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TrustedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trusted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_devices");

                    b.HasIndex("ApprovalTokenHash")
                        .HasDatabaseName("i_x_devices_approval_token_hash");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_devices_device_id");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("i_x_devices_last_used_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_devices_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_devices_user_id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("i_x_devices_user_id_device_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("i_x_devices_user_id_status");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.EmailAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_count");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("PlainTextBody")
                        .HasColumnType("text")
                        .HasColumnName("plain_text_body");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("SentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sent_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("TargetPermission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_permission");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<string>("TargetUserIds")
                        .HasColumnType("text")
                        .HasColumnName("target_user_ids");

                    b.Property<int>("TotalRecipients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_recipients");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_email_announcements");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_email_announcements_created_at");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("i_x_email_announcements_created_by_user_id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("i_x_email_announcements_sent_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_email_announcements_status");

                    b.ToTable("email_announcements", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.EmailConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRetryDlq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_retry_dlq");

                    b.Property<double>("BackoffMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(2.0)
                        .HasColumnName("backoff_multiplier");

                    b.Property<int>("CircuitBreakerFailureThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("circuit_breaker_failure_threshold");

                    b.Property<int>("CircuitBreakerOpenDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("circuit_breaker_open_duration_minutes");

                    b.Property<int>("CircuitBreakerWindowMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("circuit_breaker_window_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DlqRetryIntervalHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6)
                        .HasColumnName("dlq_retry_interval_hours");

                    b.Property<bool>("EmailsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("emails_enabled");

                    b.Property<int>("InitialRetryDelayMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("initial_retry_delay_ms");

                    b.Property<int>("MaxRetriesPerProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_retries_per_provider");

                    b.Property<int>("MaxRetryDelayMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60000)
                        .HasColumnName("max_retry_delay_ms");

                    b.Property<bool>("TestMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("test_mode");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_email_configuration");

                    b.ToTable("email_configuration", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uuid")
                        .HasColumnName("announcement_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("MovedToDlqAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moved_to_dlq_at");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_email");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid?>("SentViaProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sent_via_provider_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_name");

                    b.Property<string>("TemplateVariables")
                        .HasColumnType("text")
                        .HasColumnName("template_variables");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_email_logs");

                    b.HasIndex("AnnouncementId")
                        .HasDatabaseName("i_x_email_logs_announcement_id");

                    b.HasIndex("QueuedAt")
                        .HasDatabaseName("i_x_email_logs_queued_at");

                    b.HasIndex("RecipientEmail")
                        .HasDatabaseName("i_x_email_logs_recipient_email");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("i_x_email_logs_recipient_user_id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("i_x_email_logs_sent_at");

                    b.HasIndex("SentViaProviderId")
                        .HasDatabaseName("i_x_email_logs_sent_via_provider_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_email_logs_status");

                    b.HasIndex("TemplateName")
                        .HasDatabaseName("i_x_email_logs_template_name");

                    b.HasIndex("Status", "QueuedAt")
                        .HasDatabaseName("i_x_email_logs_status_queued_at");

                    b.ToTable("email_logs", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.EmailProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CircuitBreakerOpenUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("circuit_breaker_open_until");

                    b.Property<string>("ConfigurationEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failure_count");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_at");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("TotalFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_failed");

                    b.Property<int>("TotalSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_sent");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_email_providers");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("i_x_email_providers_is_enabled");

                    b.HasIndex("Priority")
                        .HasDatabaseName("i_x_email_providers_priority");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_email_providers_type");

                    b.HasIndex("IsEnabled", "Priority")
                        .HasDatabaseName("i_x_email_providers_is_enabled_priority");

                    b.ToTable("email_providers", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.IpRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_ip_restrictions");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("i_x_ip_restrictions_created_by_user_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_ip_restrictions_expires_at");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("i_x_ip_restrictions_ip_address");

                    b.HasIndex("Source")
                        .HasDatabaseName("i_x_ip_restrictions_source");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_ip_restrictions_type");

                    b.HasIndex("Type", "ExpiresAt")
                        .HasDatabaseName("i_x_ip_restrictions_type_expires_at");

                    b.ToTable("ip_restrictions", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.LoginPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_city");

                    b.Property<string>("LastCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_country");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_ip_address");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("last_latitude");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("last_longitude");

                    b.Property<string>("TypicalCities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("[]")
                        .HasColumnName("typical_cities");

                    b.Property<string>("TypicalCountries")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("[]")
                        .HasColumnName("typical_countries");

                    b.Property<string>("TypicalDeviceTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("[]")
                        .HasColumnName("typical_device_types");

                    b.Property<string>("TypicalHours")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("[]")
                        .HasColumnName("typical_hours");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_login_patterns");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_login_patterns_user_id");

                    b.ToTable("login_patterns", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.MagicLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_magic_link_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_magic_link_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_magic_link_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_magic_link_tokens_user_id");

                    b.HasIndex("UserId", "IsUsed", "ExpiresAt")
                        .HasDatabaseName("i_x_magic_link_tokens_user_id_is_used_expires_at");

                    b.ToTable("magic_link_tokens", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.MfaBackupCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_mfa_backup_codes");

                    b.HasIndex("UserId", "IsUsed")
                        .HasDatabaseName("i_x__mfa_backup_codes__user_id__is_used");

                    b.ToTable("mfa_backup_codes", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.Passkey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("aa_guid");

                    b.Property<long>("Counter")
                        .HasColumnType("bigint")
                        .HasColumnName("counter");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cred_type");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_passkeys");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("i_x__passkeys__credential_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x__passkeys__user_id");

                    b.ToTable("passkeys", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_password_reset_tokens");

                    b.HasIndex("CodeHash")
                        .HasDatabaseName("i_x_password_reset_tokens_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_password_reset_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_password_reset_tokens_user_id");

                    b.HasIndex("UserId", "IsUsed", "ExpiresAt")
                        .HasDatabaseName("i_x_password_reset_tokens_user_id_is_used_expires_at");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<bool>("RememberMe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("remember_me");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("SystemUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_user_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_refresh_tokens_device_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_refresh_tokens_expires_at");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("i_x_refresh_tokens_is_revoked");

                    b.HasIndex("SystemUserId")
                        .HasDatabaseName("i_x_refresh_tokens_system_user_id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("i_x_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_refresh_tokens_user_id");

                    b.HasIndex("UserType")
                        .HasDatabaseName("i_x_refresh_tokens_user_type");

                    b.HasIndex("UserId", "UserType", "IsRevoked")
                        .HasDatabaseName("i_x_refresh_tokens_user_id_user_type_is_revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_system_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("i_x_system_audit_logs_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_system_audit_logs_created_at");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("i_x_system_audit_logs_entity_type");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("i_x_system_audit_logs_target_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_system_audit_logs_user_id");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("i_x_system_audit_logs_action_created_at");

                    b.ToTable("system_audit_logs", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<JsonDocument>("PermissionIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permission_ids");

                    b.Property<DateTime?>("ResentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resent_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_system_invites");

                    b.HasIndex("AcceptedAt")
                        .HasDatabaseName("i_x_system_invites_accepted_at");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_system_invites_created_at");

                    b.HasIndex("Email")
                        .HasDatabaseName("i_x_system_invites_email");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_system_invites_expires_at");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("i_x_system_invites_invited_by");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("i_x_system_invites_revoked_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_system_invites_token_hash");

                    b.ToTable("system_invites", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_system_permissions");

                    b.HasIndex("Category")
                        .HasDatabaseName("i_x_system_permissions_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_system_permissions_name");

                    b.ToTable("system_permissions", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymized");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mfa_enabled");

                    b.Property<DateTime?>("MfaEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enabled_at");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mfa_secret");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en")
                        .HasColumnName("preferred_language");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_system_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_system_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_system_users_is_active");

                    b.HasIndex("IsAnonymized")
                        .HasDatabaseName("i_x_system_users_is_anonymized");

                    b.HasIndex("LockedUntil")
                        .HasDatabaseName("i_x_system_users_locked_until");

                    b.HasIndex("MfaEnabled")
                        .HasDatabaseName("i_x_system_users_mfa_enabled");

                    b.ToTable("system_users", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemUserPermission", b =>
                {
                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_user_id");

                    b.Property<Guid>("SystemPermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_permission_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("SystemUserId", "SystemPermissionId")
                        .HasName("p_k_system_user_permissions");

                    b.HasIndex("SystemPermissionId")
                        .HasDatabaseName("i_x_system_user_permissions_system_permission_id");

                    b.HasIndex("SystemUserId")
                        .HasDatabaseName("i_x_system_user_permissions_system_user_id");

                    b.ToTable("system_user_permissions", (string)null);
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.Device", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_devices_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.EmailAnnouncement", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_email_announcements_system_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.EmailLog", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.EmailAnnouncement", "Announcement")
                        .WithMany("EmailLogs")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_email_logs_email_announcements_announcement_id");

                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_email_logs_system_users_recipient_user_id");

                    b.HasOne("ExoAuth.Domain.Entities.EmailProvider", "SentViaProvider")
                        .WithMany()
                        .HasForeignKey("SentViaProviderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_email_logs_email_providers_sent_via_provider_id");

                    b.Navigation("Announcement");

                    b.Navigation("RecipientUser");

                    b.Navigation("SentViaProvider");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.IpRestriction", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_ip_restrictions_system_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.LoginPattern", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithOne()
                        .HasForeignKey("ExoAuth.Domain.Entities.LoginPattern", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_login_patterns_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.MagicLinkToken", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_magic_link_tokens_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.MfaBackupCode", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany("MfaBackupCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_mfa_backup_codes_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.Passkey", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany("Passkeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_passkeys_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_password_reset_tokens_system_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.Device", "Device")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_refresh_tokens_devices_device_id");

                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SystemUserId")
                        .HasConstraintName("f_k_refresh_tokens_system_users_system_user_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemAuditLog", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_system_audit_logs_system_users_target_user_id");

                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_system_audit_logs_system_users_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemInvite", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_system_invites_system_users_invited_by");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemUserPermission", b =>
                {
                    b.HasOne("ExoAuth.Domain.Entities.SystemPermission", "SystemPermission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("SystemPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_system_user_permissions_system_permissions_system_permissio~");

                    b.HasOne("ExoAuth.Domain.Entities.SystemUser", "SystemUser")
                        .WithMany("Permissions")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_system_user_permissions_system_users_system_user_id");

                    b.Navigation("SystemPermission");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.Device", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.EmailAnnouncement", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemPermission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("ExoAuth.Domain.Entities.SystemUser", b =>
                {
                    b.Navigation("MfaBackupCodes");

                    b.Navigation("Passkeys");

                    b.Navigation("Permissions");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
